Adapt database sizes to measure more around cache limits
jonaschn/tuk-power pull request #31
Opened 2018-06-13 08:59 UTC by MasterCarl

Fixes #24 
Might need some more adaptation on the power side

2018-06-13 09:06 UTC, jonaschn requested changes

2018-06-13 09:06 UTC, jonaschn commented on benchmark/main.cpp
> +        std::cerr << "benchmarking " << (size / 1024.0f) << " KB" << std::endl;
KiB instead of KB?

2018-06-13 09:06 UTC, jonaschn commented on benchmark/main.cpp
> +static const size_t DB_SIZES[] = {8 * KiB, 16 * KiB, 32 * KiB, 48 * KiB, 64 * KiB, 96 * KiB, 128 * KiB,
Could you add all the cache sizes (per Node/ per Core) as a comment?

2018-06-14 17:32 UTC, flxw commented
Any progress here?

2018-06-14 22:09 UTC, jonaschn approved these changes

2018-06-14 22:10 UTC, merged