Correct cache sizes
jonaschn/tuk-power pull request #38
Opened 2018-06-14 20:08 UTC by jonaschn

@MasterCarl @ArneMayer Could you please double check the cache sizes for the Intel machine? At least the L3 cache size looks suspicious.

2018-06-14 21:00 UTC, ArneMayer commented
![image](https://user-images.githubusercontent.com/7302856/41438155-adcc3138-7026-11e8-9b4e-fa8a6277c81d.png)

2018-06-14 21:00 UTC, ArneMayer commented
https://ark.intel.com/de/products/75258/Intel-Xeon-Processor-E7-8890-v2-37_5M-Cache-2_80-GHz

2018-06-14 21:01 UTC, ArneMayer commented
What do you mean suspicious?

2018-06-14 21:15 UTC, jonaschn commented
Ok, but then the cache sizes should be the following according to:
http://www.cpu-world.com/CPUs/Xeon/Intel-Xeon%20E7-8890%20v2.html
```
'L1': 480, # 15x 32 KiB/core
'L2': 3840, # 15x 256 KiB/core
'L3': 38400 # 15x 2,5 MiB = 37,5 MiB (shared)
```
But why then are you running just 8 and 16 threads instead of 15 and 30?

2018-06-15 21:20 UTC, MasterCarl requested changes

2018-06-15 21:20 UTC, MasterCarl commented on generate_figures.py
> +    flags = sys.argv[2:]
This will be obsolete once #46 is merged

2018-06-16 19:08 UTC, jonaschn commented
Close. #48 should be merged instead.

2018-06-16 19:08 UTC, closed without merging