Improve handling of flags in the python script
jonaschn/tuk-power pull request #46
Opened 2018-06-15 21:07 UTC by MasterCarl

2018-06-15 21:09 UTC, MasterCarl commented
See #23

2018-06-16 18:44 UTC, jonaschn requested changes

2018-06-16 18:44 UTC, jonaschn commented on generate_figures.py
> +    parser.add_argument('--system', help='system to plot results for', choices=['intel', 'power'], default='intel')
There should not be a default value.
This value should be required!
If you really want a default then use POWER ;)

2018-06-16 19:31 UTC, jonaschn approved these changes
Looks good to me

2018-06-16 19:31 UTC, merged