Fix compiler error for float definition
jonaschn/tuk-power pull request #70
Opened 2018-06-23 14:17 UTC by janetzki

`make` on our Intel machine complains about `f` for float definitions.

2018-06-23 14:23 UTC, jonaschn requested changes
This is not only an issue for Intel but also for power. But I would increase this factor, maybe at least 10000 or even 100000 times. It doesn't have a huge performance.

2018-06-23 14:30 UTC, janetzki commented
@jonaschn Done.

2018-06-23 14:41 UTC, janetzki commented
@jonaschn I changed the number.

2018-06-24 13:08 UTC, jonaschn approved these changes

2018-06-24 13:09 UTC, merged